spring:
  datasource:
    username: root
    password: Lwqiang@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todoList
  jpa:
    hibernate:
      ddl-auto: update